version: '2.3'

services:
  stan:
    image: docker.elastic.co/observability-ci/beats-integration-stan:${STAN_VERSION:-0.15.1}-1
    build:
      context: ./module/stan/_meta
      args:
        STAN_VERSION: ${STAN_VERSION:-0.15.1}
    ports:
      - 8222
