version: '2.3'

services:
  beat:
    build: ../../metricbeat
    environment:
      - BEAT_STRICT_PERMS=false
      - TEST_ENVIRONMENT=false
    working_dir: /go/src/github.com/elastic/beats/x-pack/metricbeat
    volumes:
      - ${PWD}/../..:/go/src/github.com/elastic/beats/
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host
    command: make

  # Used by base tests
  elasticsearch:
    extends:
      file: ../../metricbeat/docker-compose.yml
      service: elasticsearch

  # Used by base tests
  kibana:
    # Copied configuration from OSS metricbeat because services with depends_on
    # cannot be extended with extends
    image: docker.elastic.co/observability-ci/beats-integration-kibana:${KIBANA_VERSION:-7.4.0}-1
    build:
      context: ../../metricbeat/module/kibana/_meta
      args:
        KIBANA_VERSION: ${KIBANA_VERSION:-7.4.0}
    depends_on:
      - elasticsearch
    ports:
      - 5601

  mssql:
    image: docker.elastic.co/observability-ci/beats-integration-mssql:${MSSQL_VERSION:-2017-GA}-1
    build:
      context: ./module/mssql/_meta
      args:
        MSSQL_VERSION: ${MSSQL_VERSION:-2017-GA}
    ports:
      - 1433

  stan:
    image: docker.elastic.co/observability-ci/beats-integration-stan:${STAN_VERSION:-0.15.1}-1
    build:
      context: ./module/stan/_meta
      args:
        STAN_VERSION: ${STAN_VERSION:-0.15.1}
    ports:
      - 8222
