- module: prometheus
  period: 10s
  hosts: ["localhost:9090"]
  metricsets: ["collector"]
  metrics_path: /metrics
  #username: "user"
  #password: "secret"

  # This can be used for service account based authorization:
  #  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  #ssl.certificate_authorities:
  #  - /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt

- module: prometheus
  period: 10s
  hosts: ["localhost:9090"]
  metricsets: ["query"]
  paths:
  - name: 'instant_vector'
    path: '/api/v1/query'
    fields:
      'query': sum(rate(prometheus_http_requests_total[1m]))
  - name: 'range_vector'
    path: '/api/v1/query_range'
    fields:
      'query': 'up'
      'start': '2019-12-20T00:00:00.000Z'
      'end':  '2019-12-21T00:00:00.000Z'
      'step': 1h
  - name: 'scalar'
    path: '/api/v1/query'
    fields:
      'query': '100'